x-prod-app: &prod-app
  build:
    target: production
  image: codepraise-api-python:prod
  environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/codepraise
    - REDIS_URL=redis://redis:6379/0

services:
  # `$ docker compose -f docker-compose.yml -f docker-compose.prod.yml up`
  db:
    image: postgres:14.2-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codepraise
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-bullseye
    volumes:
      - redis:/data

  db-migrations:
    <<: *prod-app
    depends_on:
      - db
    command: ./bin/wait-for-it.sh db:5432 -- inv db.migrate -e production

  api:
    <<: *prod-app
    depends_on:
      - db-migrations
      - redis
    command: inv api.run.prod

  worker:
    <<: *prod-app
    command: inv worker.run.prod

  # `$ docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm console`
  console:
    <<: *prod-app
    command: inv console -e production

  # `$ docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm bash`
  bash:
    <<: *prod-app

volumes:
  postgres:
  redis:
