"""create tables for db_infra

Revision ID: 48fde44fa82c
Revises: 
Create Date: 2021-08-14 22:38:58.246179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48fde44fa82c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collaborators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("origin_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_collaborators_id"), "collaborators", ["id"], unique=False)
    op.create_table(
        "repos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("git_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["collaborators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("origin_id"),
    )
    op.create_index(op.f("ix_repos_id"), "repos", ["id"], unique=False)
    op.create_table(
        "repos_contributors",
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("collaborator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collaborator_id"],
            ["collaborators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
        ),
        sa.PrimaryKeyConstraint("repo_id", "collaborator_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repos_contributors")
    op.drop_index(op.f("ix_repos_id"), table_name="repos")
    op.drop_table("repos")
    op.drop_index(op.f("ix_collaborators_id"), table_name="collaborators")
    op.drop_table("collaborators")
    # ### end Alembic commands ###
