name: Test

on:
  push:
    branches: 
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pipenv run inv spec
